spring.application.name=uniride-finance-service
server.port=8084

# Base de datos independiente para Finance (Puerto 5436)
spring.datasource.url=jdbc:postgresql://localhost:5436/uniride_finance
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Seguridad compartida con IAM y Booking
jwt.secret=ThisIsASecretKeyForCampusDriveAppThatMustBeVeryLongAndSecure